import { BUSINESS, sellerLine } from "./business.js";

/**
 * The Terms of Service, Privacy Policy and Refund & Cancellation Policy, as
 * data rendered by screens/LegalScreen.jsx.
 *
 * DRAFTS, written to describe what this app actually does (checked against
 * the code: what's sent where, what's stored, for how long). They are not
 * legal advice — have a lawyer licensed in your province review them before
 * you take real payments, and keep them true whenever the app changes: a
 * privacy policy that describes a data flow the app no longer has (or misses
 * one it gained) is a problem in its own right.
 *
 * Block shapes: a string is a paragraph; `{ list: [...] }` a bullet list;
 * a paragraph may also be an array of strings and `{ text, href }` links.
 */

const link = (text, href) => ({ text, href });

function contactLines(b) {
  const lines = [`Email: ${b.contactEmail}`];
  lines.push(`Mail: ${b.mailingAddress.trim() || "[mailing address]"}`);
  if (b.phone.trim()) lines.push(`Phone: ${b.phone.trim()}`);
  return lines;
}

/* --- Terms of Service ------------------------------------------------------ */

export function termsDocument(b = BUSINESS) {
  const name = b.legalName.trim() || "[your legal name]";
  const province = b.province.trim() || "[province]";
  return {
    id: "terms",
    title: "Terms of Service",
    updated: b.effectiveDate,
    intro: [
      `${sellerLine(b)} ("we", "us"). These terms are the agreement between you and us when you use ${b.tradeName}. By creating an account or buying a plan you agree to them.`,
    ],
    sections: [
      {
        heading: "1. The service",
        blocks: [
          `${b.tradeName} offers AI-assisted mock interviews, job matching against your resume, a resume builder, progress tracking and an application tracker. Features and daily limits depend on your plan, as listed on the pricing page.`,
          "The feedback, scores, job matches and resume text are generated by AI models. They can be wrong, incomplete or inconsistent, and they are practice aids — not career, legal or professional advice, and no guarantee of an interview, a job offer or any other outcome.",
          "Job listings come from a third-party job search service (Adzuna). We don't employ, represent or vouch for the employers listed, and a listing may have closed.",
        ],
      },
      {
        heading: "2. Your account",
        blocks: [
          "You need an account to use the app. Keep your sign-in details secure; you're responsible for what happens under your account.",
          "You must be old enough to enter a binding contract where you live (the age of majority in your province or country) to buy a plan, or have a parent or guardian's permission. The service isn't intended for anyone under 16.",
        ],
      },
      {
        heading: "3. Plans, prices and automatic renewal",
        blocks: [
          "Regular is free. Pro and Ultimate are paid subscriptions, billed monthly or yearly in advance. The price, billing period and currency are shown before you pay, on our pricing page and on the checkout page.",
          "Paid plans renew automatically at the end of each billing period, at the same price, and are charged to the payment method you gave at checkout, until you cancel. Payments are processed by Stripe; we never see or store your full card details.",
          "Where we're required to collect sales tax (such as GST/HST or VAT), it is calculated from your billing address and shown at checkout before you pay.",
          "If we change the price of a plan, we'll email you at least 30 days before the change affects you. The new price applies from your next renewal after that notice; if you don't want it, cancel before then.",
          "We won't reduce the limits of a plan during a billing period you've already paid for. Any change to what a plan includes takes effect at your next renewal, with at least 30 days' notice.",
        ],
      },
      {
        heading: "4. Cancelling, refunds and downgrades",
        blocks: [
          "You can cancel at any time from Plans → Manage billing. Cancelling stops future charges; you keep your paid plan until the end of the period you've paid for, then your account moves to Regular.",
          "New subscriptions can be refunded in full within 14 days of the first payment. Other refunds are covered by our Refund & Cancellation Policy, which forms part of these terms.",
          "Moving to a lower plan never deletes your data. Features and history beyond the lower plan's limits are hidden, and come back if you upgrade again.",
          "If a renewal payment fails, Stripe will retry it for a period. If it still can't be collected, the subscription ends and your account moves to Regular.",
        ],
      },
      {
        heading: "5. Your content",
        blocks: [
          "You own what you put into the app — job descriptions, answers, resumes, notes — and what the app produces from it for you. You give us permission to store it and to send it to the AI and other service providers described in our Privacy Policy, only as needed to run the service for you.",
          "Only add content you have the right to use. Don't paste other people's personal information into the app without their permission.",
        ],
      },
      {
        heading: "6. Acceptable use",
        blocks: [
          "Don't misuse the service. In particular, don't:",
          {
            list: [
              "try to get around plan limits, rate limits or security measures, or access another person's account or data;",
              "use automated tools to send requests, or resell or redistribute the service;",
              "use it for anything unlawful, or to generate content that is harassing, hateful or infringes someone's rights;",
              "interfere with the service or the infrastructure it runs on.",
            ],
          },
          "We may suspend or close an account that breaks these rules. If we close a paid account for a reason other than a serious breach, we'll refund the unused part of the current billing period.",
        ],
      },
      {
        heading: "7. Availability and changes",
        blocks: [
          "We work to keep the service available but can't promise it will always be uninterrupted or error-free. We may change or discontinue features. If we discontinue a paid plan, we'll give at least 30 days' notice and refund any prepaid period you can't use.",
        ],
      },
      {
        heading: "8. Liability",
        blocks: [
          "To the extent the law allows, the service is provided \"as is\", and we aren't liable for indirect or consequential losses, or for decisions you make based on AI-generated content. Our total liability for any claim relating to the service is limited to the amount you paid us in the 12 months before the claim.",
          "Nothing in these terms limits any right you have under consumer protection law that can't be waived or limited by contract.",
        ],
      },
      {
        heading: "9. Governing law",
        blocks: [
          `These terms are governed by the laws of ${province} and the federal laws of Canada that apply there. If you're a consumer living elsewhere, you also keep the protection of the mandatory laws where you live.`,
        ],
      },
      {
        heading: "10. Changes to these terms",
        blocks: [
          "If we make a material change, we'll tell you by email or in the app at least 30 days before it takes effect. If you don't agree, you can cancel before then.",
        ],
      },
      {
        heading: "11. Contact",
        blocks: [`${name} (${b.tradeName})`, { list: contactLines(b) }],
      },
    ],
  };
}

/* --- Privacy Policy -------------------------------------------------------- */

export function privacyDocument(b = BUSINESS) {
  const name = b.legalName.trim() || "[your legal name]";
  return {
    id: "privacy",
    title: "Privacy Policy",
    updated: b.effectiveDate,
    intro: [
      `${sellerLine(b)}. This policy explains what personal information ${b.tradeName} collects, why, who it's shared with, and your rights. We follow Canada's Personal Information Protection and Electronic Documents Act (PIPEDA) and, where they apply to you, provincial privacy laws.`,
    ],
    sections: [
      {
        heading: "What we collect",
        blocks: [
          {
            list: [
              "Account: your email address and password (stored hashed by our sign-in provider), or the name, email and profile picture your Google or GitHub account shares when you sign in with it.",
              "What you put in: job descriptions, interview answers (typed, or transcribed from speech), resume text, Resume Builder messages and documents, Application Tracker entries, and — if you choose to take it — career survey answers.",
              "What the app produces for you: interview questions, scores and feedback, job match scores, resume drafts.",
              "Speak mode measurements: for each spoken answer, five numbers (speaking pace, pause count and total pause time, speaking time, and the share of time you faced the camera). Your camera and microphone are never recorded or uploaded; these numbers are measured in your browser.",
              "Billing: which plan you're on, your subscription status and renewal dates, and the identifier Stripe gives your customer account. Your card details go to Stripe and never reach us.",
              "Usage: counts of what you used today (interviews, job searches, Resume Builder messages) to apply your plan's daily limits, and your IP address in short-lived memory for rate limiting.",
            ],
          },
        ],
      },
      {
        heading: "How we use it",
        blocks: [
          "To provide the service (generating questions, feedback, matches and resumes), to keep your history and progress, to apply your plan and bill you, to prevent abuse, and to answer you when you contact us. We don't sell your personal information, and we don't use it for advertising.",
          "If you complete the career survey, we may send you one follow-up email asking you to rate the site.",
        ],
      },
      {
        heading: "Who we share it with",
        blocks: [
          "Only the service providers the app needs to work, each receiving only what its part requires:",
          {
            list: [
              "Supabase — sign-in and account data, survey answers, Application Tracker entries and plan records.",
              "OpenRouter and the AI model providers it routes to — the text needed for each request (job descriptions, answers, resume text, Resume Builder messages, feedback being summarised).",
              "Stripe — your email, billing address and payment details, to process payments and tax.",
              "Adzuna — the job search keywords derived from your resume, and the city and country you search in (not the resume itself).",
              "Your browser's speech recognition service (Google, in Chrome) — the audio of spoken answers, to transcribe them. This comes from your browser, not from us.",
              "Our hosting provider, which runs the servers that store your interview history.",
              "n8n and our email provider — your email address, only if you completed the career survey, to send the one rating email.",
              "When you use Speak mode, the face-tracking model is downloaded from jsDelivr and Google, and fonts load from Google Fonts; those requests share your IP address with them, as any web request does.",
            ],
          },
          "We may also disclose information if the law requires it.",
        ],
      },
      {
        heading: "Where it's stored",
        blocks: [
          "Our service providers may store and process information outside Canada, including in the United States, where it is subject to the laws of that country and may be accessible to its authorities.",
        ],
      },
      {
        heading: "How long we keep it",
        blocks: [
          {
            list: [
              "Interviews: until you delete them. Each account keeps its 100 most recent; older ones are removed automatically.",
              "Resume for Job Matches: in your own browser only, for up to 7 days. Resume Builder drafts: in your browser tab only, until you close it.",
              "Survey answers, tracker entries and account data: until you delete them or ask us to delete your account.",
              "Billing records: as long as tax law requires (in Canada, generally six years).",
              "Daily usage counts: until the end of the day. Rate-limiting data: minutes.",
            ],
          },
        ],
      },
      {
        heading: "Stored in your browser",
        blocks: [
          "The app uses your browser's local and session storage to keep you signed in, remember your preferences, restore an interview or a resume draft after a refresh, and cache your Job Matches resume for 7 days. It doesn't use advertising or analytics trackers.",
        ],
      },
      {
        heading: "Your rights",
        blocks: [
          "You can ask to see the personal information we hold about you, correct it, or have your account and its data deleted, and you can withdraw your consent to its use (which may mean we can no longer provide the service). Email us and we'll respond within 30 days.",
          [
            "If you're not satisfied with our answer, you can complain to the ",
            link("Office of the Privacy Commissioner of Canada", "https://www.priv.gc.ca/"),
            " or, where it applies, your provincial privacy commissioner (for example, the Commission d'accès à l'information in Quebec).",
          ],
        ],
      },
      {
        heading: "Security",
        blocks: [
          "Data is sent over encrypted connections, access is restricted to the account it belongs to, and payment details are handled only by Stripe. No system is perfectly secure; if a breach creates a real risk of significant harm to you, we'll tell you and the Privacy Commissioner as the law requires.",
        ],
      },
      {
        heading: "Changes",
        blocks: [
          "If we change this policy in a way that matters, we'll tell you by email or in the app before the change takes effect.",
        ],
      },
      {
        heading: "Contact — privacy officer",
        blocks: [
          `${name} is responsible for personal information at ${b.tradeName}.`,
          { list: contactLines(b) },
        ],
      },
    ],
  };
}

/* --- Refund & Cancellation Policy ----------------------------------------- */

export function refundDocument(b = BUSINESS) {
  return {
    id: "refunds",
    title: "Refund & Cancellation Policy",
    updated: b.effectiveDate,
    intro: [
      `How cancelling and refunds work for ${b.tradeName} Pro and Ultimate. This policy is part of our Terms of Service.`,
    ],
    sections: [
      {
        heading: "Cancel any time",
        blocks: [
          "Go to Plans → Manage billing and choose Cancel. It takes effect at the end of the period you've already paid for: there are no further charges, and you keep your plan until then. After that your account moves to Regular, the free plan.",
          "Cancelling never deletes your data. Interviews, applications and resumes stay saved; anything beyond Regular's limits is hidden and comes back if you upgrade again.",
        ],
      },
      {
        heading: "14-day refund on new subscriptions",
        blocks: [
          "If you're not happy, email us within 14 days of the first payment for a new Pro or Ultimate subscription (monthly or yearly) and we'll refund that payment in full and end the subscription. No reason needed.",
          "If you live in the EU or the UK, this also covers your legal 14-day right to withdraw from an online purchase.",
        ],
      },
      {
        heading: "Renewals",
        blocks: [
          "Before a yearly plan renews, we send a reminder email. Renewal payments aren't refunded, except:",
          {
            list: [
              "if you were charged after you had cancelled, or charged twice for the same period;",
              "if the service was unavailable for a significant part of the period;",
              "where the law requires a refund.",
            ],
          },
        ],
      },
      {
        heading: "Switching plans",
        blocks: [
          "You can switch between Pro and Ultimate, or between monthly and yearly billing, in Manage billing. The change is prorated: you're credited for the unused time on your old plan.",
        ],
      },
      {
        heading: "How to ask for a refund",
        blocks: [
          `Email ${b.contactEmail} from the address on your account. We reply within 2 business days and issue approved refunds to your original payment method within 5 business days; your bank may take another 5–10 days to show it.`,
        ],
      },
    ],
  };
}

export const LEGAL_DOCUMENTS = {
  terms: termsDocument,
  privacy: privacyDocument,
  refunds: refundDocument,
};
